// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iflhdbjxonqtldorajuc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlmbGhkYmp4b25xdGxkb3JhanVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MDI1NDgsImV4cCI6MjA2MTA3ODU0OH0.dYpbRgXBgIAibYoLI3vGvY5UPAQ-Mj5FTM3M4x2CdDM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);